### ISSUE TITLE
fix `npm install` error: "Error: oniguruma@6.2.1 install: `node-gyp rebuild`"

### ISSUE THREAD

**Issue by cvan** [immersive-web/webvrrocks#302]
<details open>

```

24635 verbose stack Error: oniguruma@6.2.1 install: `node-gyp rebuild`
24635 verbose stack Exit status 1
24635 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
24635 verbose stack     at EventEmitter.emit (events.js:182:13)
24635 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
24635 verbose stack     at ChildProcess.emit (events.js:182:13)
24635 verbose stack     at maybeClose (internal/child_process.js:947:16)
24635 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
24636 verbose pkgid oniguruma@6.2.1
24637 verbose cwd /opt/webvrrocks/webvrrocks
24638 verbose Darwin 17.3.0
24639 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
24640 verbose node v10.0.0
24641 verbose npm  v6.4.1
24642 error code ELIFECYCLE
24643 error errno 1
24644 error oniguruma@6.2.1 install: `node-gyp rebuild`
24644 error Exit status 1
24645 error Failed at the oniguruma@6.2.1 install script.
24645 error This is probably not a problem with npm. There is likely additional logging output above.
24646 verbose exit [ 1, true ]

```

</details>

**Comment by caseyyee** [comment]
I had to install node 8 for it to work.
